id: PFC53ECE3
initial_creation_type: input
source_metadata:
  title: Turning Back the Summons
  language: en
  description: 'Texts related to the practice of ‘turning back the summons’ or ‘averting
    the call’ (sun bzlog) of the ḍākinīs:'
  volume:
    cfd77d84bff04cecb35b0bcc0ec67ffc:
      title: Brief Turning Back the Summons
      parent: Practices
    0af7c0ca07054edb95e0c8c799dae68c:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Prayers
created_at: '2022-03-01T06:27:35.576952'
last_modified_at: '2022-03-01T06:27:35.576958'
